# Generated by Django 5.0.6 on 2024-06-13 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
