# Generated by Django 5.0.6 on 2024-06-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Published", "Published"), ("Draft", "Draft")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
