# Generated by Django 5.0.6 on 2024-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0005_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=250),
        ),
    ]
