# Generated by Django 5.0.6 on 2024-06-12 21:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_sociallink_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_body",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="short_description",
            field=models.TextField(max_length=100),
        ),
    ]
