# Generated by Django 5.0.6 on 2024-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0009_alter_blog_blog_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_body",
            field=models.TextField(max_length=1000),
        ),
    ]
