# Generated by Django 5.0.6 on 2024-06-13 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0011_category_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_by",
        ),
    ]
